# Generated by Django 4.2 on 2023-04-12 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_vehicle_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='conductor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.driver'),
        ),
    ]
